# Generated by Django 4.2.1 on 2023-05-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogIn',
            new_name='LogIns',
        ),
    ]
